name: BuildTest

on:
  push:
    branches: [ master, dev, checkpoint_2 ]
  pull_request:
    branches: [ master, dev ]
jobs:
  Build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: "Build main project"
        run : |
          sudo apt-get install libsfml-dev
          chmod +x run.sh
          ./run.sh
      - name: "Build and run tests"
        run : |
          git clone https://github.com/google/googletest
          cd googletest
          cd googletest
          cmake ..
          make
          sudo make install
          cd ../../
          cd tests
          mkdir buildTest
          cd buildTest
          cmake ..
          make
          ./Test
  Build-macOs:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: "Build main project"
        run : |
          brew install sfml
          chmod +x run.sh
          ./run.sh
          
